"""
Authoritative Rule Registry with Complete Legal Source Traceability.
Provides verified statutory citations, effective dates, verification status,
and authoritative source links for Rule 6 and related provisions under PCR 2011.
"""

from typing import Dict, Any, List
from .sources import AUTHORITATIVE_LEGAL_SOURCES

STATUTORY_RULES_REGISTRY: List[Dict[str, Any]] = [
    {
        "rule_id": "RULE_6_1_A",
        "rule_number": "Rule 6(1)(a)",
        "rule_reference": "Rule 6(1)(a), Legal Metrology (Packaged Commodities) Rules, 2011",
        "title": "Name and Generic Identity of the Commodity",
        "description": "Every package shall bear the name and generic identity of the commodity contained therein on the Principal Display Panel.",
        "statutory_mandate": "MANDATORY_ON_PDP",
        "jurisdiction": "Republic of India / Ministry of Consumer Affairs",
        "source_id": "LM_PCR_2011",
        "source_name": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["name"],
        "source_url": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["official_url"],
        "source_version": "2011 As Amended",
        "effective_date": "2011-04-01",
        "last_verified_at": "2026-03-01",
        "verification_status": "VERIFIED",
        "statutory_penalty_ref": "Section 36(1) of The Legal Metrology Act, 2009",
        "prescribed_font_applicable": True,
    },
    {
        "rule_id": "RULE_6_1_B",
        "rule_number": "Rule 6(1)(b) & Rule 11",
        "rule_reference": "Rule 6(1)(b) & Rule 11, LM (Packaged Commodities) Rules, 2011",
        "title": "Net Quantity in Standard Units of Weight or Measure",
        "description": "The net quantity, in terms of standard unit of weight or measure, of the commodity contained in the package shall be declared with prescribed font size and unit symbols (g, kg, ml, l, m, or numbers).",
        "statutory_mandate": "MANDATORY_ON_PDP",
        "jurisdiction": "Republic of India / Ministry of Consumer Affairs",
        "source_id": "LM_PCR_2011",
        "source_name": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["name"],
        "source_url": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["official_url"],
        "source_version": "2011 As Amended",
        "effective_date": "2011-04-01",
        "last_verified_at": "2026-03-01",
        "verification_status": "VERIFIED",
        "statutory_penalty_ref": "Section 36(1) of The Legal Metrology Act, 2009",
        "prescribed_font_applicable": True,
    },
    {
        "rule_id": "RULE_6_1_DA",
        "rule_number": "Rule 6(1)(da) & Rule 18",
        "rule_reference": "Rule 6(1)(da) & Rule 18, LM (Packaged Commodities) Rules, 2011",
        "title": "Maximum Retail Price (MRP) Inclusive of All Taxes",
        "description": "The maximum retail price at which the commodity in packaged form may be sold to the consumer, inclusive of all taxes, declared as 'MRP ₹... incl. of all taxes'. Dual pricing on identical packages is prohibited.",
        "statutory_mandate": "MANDATORY",
        "jurisdiction": "Republic of India / Ministry of Consumer Affairs",
        "source_id": "LM_PCR_2011",
        "source_name": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["name"],
        "source_url": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["official_url"],
        "source_version": "2011 As Amended (2021 USP Norms)",
        "effective_date": "2011-04-01",
        "last_verified_at": "2026-03-01",
        "verification_status": "VERIFIED",
        "statutory_penalty_ref": "Section 36(1) & Section 36(2) of The Legal Metrology Act, 2009",
        "prescribed_font_applicable": True,
    },
    {
        "rule_id": "RULE_6_1_D",
        "rule_number": "Rule 6(1)(d)",
        "rule_reference": "Rule 6(1)(d), Legal Metrology (Packaged Commodities) Rules, 2011",
        "title": "Month and Year of Manufacture / Packaging / Import",
        "description": "The month and year in which the commodity is manufactured or pre-packed or imported shall be clearly indicated on every package.",
        "statutory_mandate": "MANDATORY",
        "jurisdiction": "Republic of India / Ministry of Consumer Affairs",
        "source_id": "LM_PCR_2011",
        "source_name": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["name"],
        "source_url": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["official_url"],
        "source_version": "2011 As Amended",
        "effective_date": "2011-04-01",
        "last_verified_at": "2026-03-01",
        "verification_status": "VERIFIED",
        "statutory_penalty_ref": "Section 36(1) of The Legal Metrology Act, 2009",
        "prescribed_font_applicable": False,
    },
    {
        "rule_id": "RULE_6_1_E",
        "rule_number": "Rule 6(1)(e)",
        "rule_reference": "Rule 6(1)(e), Legal Metrology (Packaged Commodities) Rules, 2011",
        "title": "Name and Complete Address of Manufacturer / Packer / Importer",
        "description": "The name and complete physical address of the manufacturer or packer, or where the manufacturer is not the packer, the name and address of the manufacturer and packer, or for imported packages, the importer name and address with postal PIN code.",
        "statutory_mandate": "MANDATORY",
        "jurisdiction": "Republic of India / Ministry of Consumer Affairs",
        "source_id": "LM_PCR_2011",
        "source_name": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["name"],
        "source_url": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["official_url"],
        "source_version": "2011 As Amended",
        "effective_date": "2011-04-01",
        "last_verified_at": "2026-03-01",
        "verification_status": "VERIFIED",
        "statutory_penalty_ref": "Section 36(1) of The Legal Metrology Act, 2009",
        "prescribed_font_applicable": False,
    },
    {
        "rule_id": "RULE_6_1_N",
        "rule_number": "Rule 6(1)(n)",
        "rule_reference": "Rule 6(1)(n), Legal Metrology (Packaged Commodities) Rules, 2011",
        "title": "Consumer Care Details for Grievance Redressal",
        "description": "Name, address, telephone number and e-mail address of the person who can be contacted by the consumer in case of consumer complaints or queries.",
        "statutory_mandate": "MANDATORY",
        "jurisdiction": "Republic of India / Ministry of Consumer Affairs",
        "source_id": "LM_PCR_2011",
        "source_name": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["name"],
        "source_url": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["official_url"],
        "source_version": "2011 As Amended",
        "effective_date": "2011-04-01",
        "last_verified_at": "2026-03-01",
        "verification_status": "VERIFIED",
        "statutory_penalty_ref": "Section 36(1) of The Legal Metrology Act, 2009",
        "prescribed_font_applicable": False,
    },
    {
        "rule_id": "RULE_6_1_C",
        "rule_number": "Rule 6(1)(c)",
        "rule_reference": "Rule 6(1)(c), Legal Metrology (Packaged Commodities) Rules, 2011",
        "title": "Country of Origin / Country of Manufacture",
        "description": "Declaration of Country of Origin or Country of Manufacture or Assembly on imported and domestic pre-packaged commodities.",
        "statutory_mandate": "MANDATORY",
        "jurisdiction": "Republic of India / Ministry of Consumer Affairs",
        "source_id": "LM_PCR_2011",
        "source_name": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["name"],
        "source_url": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["official_url"],
        "source_version": "2017 Amendment (GSR 629(E))",
        "effective_date": "2018-01-01",
        "last_verified_at": "2026-03-01",
        "verification_status": "VERIFIED",
        "statutory_penalty_ref": "Section 36(1) of The Legal Metrology Act, 2009",
        "prescribed_font_applicable": False,
    },
    {
        "rule_id": "RULE_6_1_F",
        "rule_number": "Rule 6(1)(f)",
        "rule_reference": "Rule 6(1)(f), Legal Metrology (Packaged Commodities) Rules, 2011",
        "title": "Best Before / Use By Date / Expiry Declaration",
        "description": "Mandatory declaration of the best before or use by date, month and year for commodities that may become unfit for human consumption after a period of time.",
        "statutory_mandate": "MANDATORY_FOR_PERISHABLES",
        "jurisdiction": "Republic of India / Ministry of Consumer Affairs",
        "source_id": "LM_PCR_2011",
        "source_name": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["name"],
        "source_url": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["official_url"],
        "source_version": "2011 As Amended",
        "effective_date": "2011-04-01",
        "last_verified_at": "2026-03-01",
        "verification_status": "VERIFIED",
        "statutory_penalty_ref": "Section 36(1) of The Legal Metrology Act, 2009",
        "prescribed_font_applicable": False,
    },
    {
        "rule_id": "RULE_6_10",
        "rule_number": "Rule 6(10)",
        "rule_reference": "Rule 6(10), Legal Metrology (Packaged Commodities) Rules, 2011",
        "title": "Mandatory E-Commerce Marketplace Declarations",
        "description": "An e-commerce entity shall ensure that all mandatory declarations under sub-rule (1) except the month and year of manufacture or packing are displayed on the digital marketplace platform.",
        "statutory_mandate": "MANDATORY_E_COMMERCE",
        "jurisdiction": "Republic of India / Ministry of Consumer Affairs",
        "source_id": "LM_PCR_2011",
        "source_name": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["name"],
        "source_url": AUTHORITATIVE_LEGAL_SOURCES["LM_PCR_2011"]["official_url"],
        "source_version": "2017 Amendment (GSR 629(E))",
        "effective_date": "2018-01-01",
        "last_verified_at": "2026-03-01",
        "verification_status": "VERIFIED",
        "statutory_penalty_ref": "Section 36(1) of The Legal Metrology Act, 2009",
        "prescribed_font_applicable": False,
    },
]


def get_rule_by_id(rule_id: str) -> Dict[str, Any]:
    for r in STATUTORY_RULES_REGISTRY:
        if r["rule_id"] == rule_id:
            return r
    return {}
